name = "jeremywoolley"
main = "worker.js"
compatibility_date = "2026-03-28"

routes = [
  { pattern = "jeremywoolley.com/*", zone_name = "jeremywoolley.com" },
  { pattern = "www.jeremywoolley.com/*", zone_name = "jeremywoolley.com" },
]

[assets]
directory = "./src"
binding = "ASSETS"
